<dec f='include/c++/4.8.2/bits/functexcept.h' l='101' type='void std::__throw_bad_function_call()'/>
<use f='include/c++/4.8.2/functional' l='2470' u='c' c='_ZNKSt8functionIFT_DpT0_EEclES2_'/>
<doc f='include/c++/4.8.2/bits/functexcept.h' l='99'>// Helpers for exception objects in &lt;functional&gt;</doc>
