<def f='include/boost/exception/exception.hpp' l='93' ll='105'/>
<def f='include/boost/exception/exception.hpp' l='107' ll='119'/>
<def f='include/boost/exception/exception.hpp' l='121' ll='133'/>
<size>4</size>
<mbr r='boost::error_info::v_' o='0' t='boost::error_info&lt;boost::throw_function_, const char *&gt;::value_type'/>
<fun r='_ZN5boost10error_infoINS_15throw_function_EPKcEC1ES3_'/>
<mbr r='boost::error_info::v_' o='0' t='boost::error_info&lt;boost::throw_file_, const char *&gt;::value_type'/>
<fun r='_ZN5boost10error_infoINS_11throw_file_EPKcEC1ES3_'/>
<mbr r='boost::error_info::v_' o='0' t='boost::error_info&lt;boost::throw_line_, int&gt;::value_type'/>
<fun r='_ZN5boost10error_infoINS_11throw_line_EiEC1Ei'/>
