<inh f='include/c++/4.8.2/stdexcept' l='112' c='std::runtime_error'/>
<def f='include/boost/function/function_base.hpp' l='739' ll='743'/>
<size>16</size>
<doc f='include/boost/function/function_base.hpp' l='735'>/**
 * The bad_function_call exception class is thrown when a boost::function
 * object is invoked
 */</doc>
<fun r='_ZN5boost17bad_function_callC1Ev'/>
