<use f='include/boost/exception/exception.hpp' l='34' u='c' c='_ZN5boost16exception_detail12refcount_ptrD1Ev'/>
<use f='include/boost/exception/exception.hpp' l='53' u='c' c='_ZN5boost16exception_detail12refcount_ptr5adoptEPT_'/>
<def f='include/boost/exception/exception.hpp' l='75' ll='80' type='void boost::exception_detail::refcount_ptr::release()'/>
