<def f='include/boost/exception/exception.hpp' l='114' ll='118' type='void boost::error_info&lt;boost::throw_file_, const char *&gt;::error_info(boost::error_info&lt;boost::throw_file_, const char *&gt;::value_type v)'/>
<use f='include/boost/throw_exception.hpp' l='90' u='c' c='_ZN5boost16exception_detail16throw_exception_ERKT_PKcS5_i'/>
