<def f='include/boost/exception/exception.hpp' l='100' ll='104' type='void boost::error_info&lt;boost::throw_function_, const char *&gt;::error_info(boost::error_info&lt;boost::throw_function_, const char *&gt;::value_type v)'/>
<use f='include/boost/throw_exception.hpp' l='89' u='c' c='_ZN5boost16exception_detail16throw_exception_ERKT_PKcS5_i'/>
