<dec f='include/c++/4.8.2/bits/exception_ptr.h' l='67' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<dec f='include/c++/4.8.2/bits/exception_ptr.h' l='87' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<use f='include/c++/4.8.2/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<use f='include/c++/4.8.2/future' l='598' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
<doc f='include/c++/4.8.2/bits/exception_ptr.h' l='66'>/// Throw the object pointed to by the exception_ptr.</doc>
