<inh f='include/c++/4.8.2/exception' l='60' c='std::exception'/>
<def f='include/c++/4.8.2/stdexcept' l='112' ll='127'/>
<ovr f='include/c++/4.8.2/stdexcept' l='130' c='std::range_error'/>
<ovr f='include/c++/4.8.2/stdexcept' l='138' c='std::overflow_error'/>
<ovr f='include/c++/4.8.2/stdexcept' l='146' c='std::underflow_error'/>
<ovr f='include/boost/system/system_error.hpp' l='22' c='boost::system::system_error'/>
<ovr f='include/c++/4.8.2/system_error' l='309' c='std::system_error'/>
<size>16</size>
<doc f='include/c++/4.8.2/stdexcept' l='107'>/** Runtime errors represent problems outside the scope of a program;
   *  they cannot be easily predicted and can generally only be caught as
   *  the program executes.
   *  @brief One of two subclasses of exception.
   */</doc>
<mbr r='std::runtime_error::_M_msg' o='64' t='std::string'/>
<fun r='_ZNSt13runtime_errorC1ERKSs'/>
<fun r='_ZNSt13runtime_errorD1Ev'/>
<fun r='_ZNKSt13runtime_error4whatEv'/>
<ovr f='include/boost/function/function_base.hpp' l='739' c='boost::bad_function_call'/>
