<inh f='include/c++/4.8.2/exception' l='60' c='std::exception'/>
<def f='vpp_1804/src/vpp-api/vapi/vapi.hpp' l='67' ll='74'/>
<size>8</size>
<fun r='_ZNK4vapi27Msg_not_available_exception4whatEv'/>
